/**
 * Common Multiplayer Manager for NeuroFlux Games
 * Handles rooms, player management, game state sync
 */

// Game room registry
export const rooms = new Map();
export const players = new Map();

/**
 * Create or join game room
 * @param {socket} socket - Socket.IO socket instance
 * @param {string} roomId - Explicit room ID (generated by matchmaker)
 * @param {string} gameName - Game identifier
 * @param {object} playerData - Player metadata
 * @returns {{roomId, room, isCreator}}
 */
export const createOrJoinRoom = (socket, roomId, gameName, playerData) => {
  if (!rooms.has(roomId)) {
    rooms.set(roomId, {
      gameName,
      players: new Set(),
      state: 'waiting',
      maxPlayers: 2,
      creator: socket.id
    });
  }

  const room = rooms.get(roomId);
  room.players.add(socket.id);
  players.set(socket.id, { roomId, ...playerData });

  socket.join(roomId);
  socket.roomId = roomId;

  return { roomId, room, isCreator: socket.id === room.creator };
};

/**
 * Leave room and cleanup
 * @param {socket} socket - Socket.IO socket instance
 * @param {object} options - Optional configuration
 * @param {boolean} options.notifyOthers - Whether to notify remaining players
 * @param {object} options.io - Socket.IO server instance (required if notifyOthers is true)
 * @param {string} options.reason - Reason for leaving
 * @param {string} options.message - Custom message to send to opponents
 */
export const leaveRoom = (socket, options = {}) => {
  const { 
    notifyOthers = false, 
    io = null, 
    reason = 'playerLeft',
    message = 'Your opponent has disconnected'
  } = options;

  if (!players.has(socket.id)) return;

  const player = players.get(socket.id);
  const roomId = player?.roomId;
  const room = rooms.get(roomId);

  if (room) {
    // Notify other players in the room before leaving
    if (notifyOthers && io && roomId) {
      socket.to(roomId).emit('opponentDisconnected', {
        playerId: socket.id,
        reason,
        message
      });
    }

    room.players.delete(socket.id);

    // Delete room if empty
    if (room.players.size === 0) {
      rooms.delete(roomId);
    }
  }

  // Clean player reference
  players.delete(socket.id);

  // Clean socket references
  if (socket.roomId) {
    socket.leave(socket.roomId);
    socket.roomId = null;
  }
};

/**
 * Broadcast room state to all players in room
 * @param {io} io - Socket.IO server instance
 * @param {string} roomId - Room identifier
 * @param {object} stateUpdate - Data to broadcast
 */
export const broadcastRoomState = (io, roomId, stateUpdate) => {
  io.to(roomId).emit('roomUpdate', stateUpdate);
};

/**
 * Get remaining players in a room (excluding a specific player)
 * @param {string} roomId - Room identifier
 * @param {string} excludePlayerId - Player ID to exclude
 * @returns {Array} Array of remaining player IDs
 */
export const getRemainingPlayers = (roomId, excludePlayerId) => {
  const room = rooms.get(roomId);
  if (!room) return [];
  return Array.from(room.players).filter(id => id !== excludePlayerId);
};

/**
 * Force cleanup a room and all its players
 * @param {string} roomId - Room identifier
 * @param {object} io - Socket.IO server instance (optional, for notifications)
 * @param {string} reason - Reason for cleanup
 */
export const cleanupRoom = (roomId, io = null, reason = 'roomClosed') => {
  const room = rooms.get(roomId);
  if (!room) return;

  // Notify all players before cleanup
  if (io) {
    io.to(roomId).emit('roomClosed', {
      roomId,
      reason,
      message: 'The room has been closed'
    });
  }

  // Clean up all players in the room
  room.players.forEach((playerId) => {
    const playerData = players.get(playerId);
    if (playerData) {
      players.delete(playerId);
    }
  });

  // Delete the room
  rooms.delete(roomId);
};

export default { createOrJoinRoom, leaveRoom, broadcastRoomState, rooms, players, getRemainingPlayers, cleanupRoom };

